spring:
  application.name: web-scraper
  profiles.active: ${ACTIVE_PROFILE:dev}

server:
  servlet:
    context-path: /api/v1

imdb:
  baseUrl: {IMDB_BASEURL:https://www.imdb.com/}
  searchLimit: {IMDB_SEARCH_LIMIT:5}
